# Generated by Django 3.2.13 on 2022-05-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220507_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='kcookpost',
            name='introduction',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
