# Generated by Django 3.2.13 on 2022-05-09 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_kcookpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categrory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product_imgs/')),
                ('price', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('product_des', models.TextField()),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categrory')),
            ],
        ),
    ]
