# Generated by Django 3.2.13 on 2022-05-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_kcookpost_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcookpost',
            name='introduction',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
